"""
Tests for the PRAW-based Reddit publisher.

Usage:
    # Credential check only  (no post created)
    python tests/test_reddit_publisher.py --check

    # Full live post  (requires all REDDIT_* vars in .env)
    python tests/test_reddit_publisher.py --live

    # Live post to a specific subreddit (e.g. a test/sandbox sub you own)
    python tests/test_reddit_publisher.py --live --subreddit test
"""

import sys
import logging
import argparse
from pathlib import Path
from datetime import datetime

# ── project root on path ─────────────────────────────────────────────────
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

try:
    from dotenv import load_dotenv
    load_dotenv(project_root / ".env")
except ImportError:
    pass

from src.utils.reddit_publisher import RedditPublisher, RedditPublishError

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(name)s  %(levelname)s  %(message)s",
)
logger = logging.getLogger("test_reddit_publisher")

# ── Sample article ────────────────────────────────────────────────────────

SAMPLE_TITLE = (
    f"[TEST] AI Newsroom Auto-Post — {datetime.now().strftime('%Y-%m-%d %H:%M')}"
)

SAMPLE_MARKDOWN = """\
## AI Newsroom — Automated Publishing Test

This is a brief test post generated by **AI Newsroom**, a multi-agent
pipeline that scouts, researches, writes, and publishes technology articles.

### What just happened?

1. A Scout agent found a trending topic.
2. A Researcher agent gathered sources.
3. A Writer + Editor pair drafted and polished the article.
4. A Publisher agent submitted it here via the Reddit API (PRAW).

This is a harmless test post — feel free to ignore or remove it.
"""


# ── Test functions ────────────────────────────────────────────────────────

def test_import() -> bool:
    """Verify praw is installed and RedditPublisher imports cleanly."""
    logger.info("=" * 60)
    logger.info("TEST: Import & dependency check")
    logger.info("=" * 60)
    try:
        import praw  # noqa: F401
        logger.info("  ✅ praw is installed")
        logger.info("  ✅ RedditPublisher imported successfully")
        return True
    except ImportError as e:
        logger.error(f"  ❌ {e}")
        logger.error("  Run: pip install praw")
        return False


def test_credential_check(subreddit: str = "artificial") -> bool:
    """Verify credentials authenticate without posting."""
    logger.info("\n" + "=" * 60)
    logger.info("TEST: Credential verification (no post)")
    logger.info("=" * 60)
    publisher = RedditPublisher(subreddit=subreddit)
    ok = publisher.verify_credentials()
    if ok:
        logger.info("  ✅ Credentials valid")
    else:
        logger.error("  ❌ Credential check failed — see above for details")
    return ok


def test_live_post(subreddit: str = "artificial") -> bool:
    """Actually submit a test post to Reddit."""
    logger.info("\n" + "=" * 60)
    logger.info(f"TEST: Live post to r/{subreddit}")
    logger.info("=" * 60)

    try:
        publisher = RedditPublisher(subreddit=subreddit)
        url = publisher.publish(
            title=SAMPLE_TITLE,
            content_markdown=SAMPLE_MARKDOWN,
        )
        logger.info(f"\n  ✅ Post published: {url}")
        return True
    except RedditPublishError as e:
        logger.error(f"\n  ❌ RedditPublishError: {e}")
        return False
    except Exception as e:
        logger.error(f"\n  ❌ Unexpected error: {e}", exc_info=True)
        return False


# ── Entry point ───────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Test the PRAW-based Reddit publisher"
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--check",
        action="store_true",
        help="Verify credentials only, do not post",
    )
    group.add_argument(
        "--live",
        action="store_true",
        help="Submit a real test post to Reddit",
    )
    parser.add_argument(
        "--subreddit",
        default="",
        help="Target subreddit (overrides REDDIT_SUBREDDIT env var)",
    )
    args = parser.parse_args()

    import os
    subreddit = args.subreddit or os.getenv("REDDIT_SUBREDDIT", "artificial")

    results: dict[str, bool] = {}

    # Always check import
    results["import"] = test_import()
    if not results["import"]:
        sys.exit(1)

    if args.check or not args.live:
        results["credentials"] = test_credential_check(subreddit)

    if args.live:
        results["credentials"] = test_credential_check(subreddit)
        if results["credentials"]:
            results["live_post"] = test_live_post(subreddit)
        else:
            logger.error("Skipping live post — credentials invalid.")
            results["live_post"] = False

    # ── Summary ──
    logger.info("\n" + "=" * 60)
    logger.info("SUMMARY")
    logger.info("=" * 60)
    for name, ok in results.items():
        logger.info(f"  {'✅ PASS' if ok else '❌ FAIL'}  {name}")

    sys.exit(0 if all(results.values()) else 1)


if __name__ == "__main__":
    main()
